# Generated by Django 5.0.4 on 2024-04-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "tasks",
                "default_related_name": "tasks",
            },
        ),
    ]
